### ISSUE TITLE
Remove log messages of not installed packages

### ISSUE THREAD

**Issue by craig77** [php-http/discovery#133] opened 2019-01-10 09:17 UTC
Hi,

I installed mailgun/mailgun-php https://github.com/mailgun/mailgun-php using it's recommended line below

php composer.phar require mailgun/mailgun-php php-http/curl-client guzzlehttp/psr7

This all works fine for me. In the logs though I see loads of notice messages around Nyholm not loading which is correct cause I didn't require it when running the above command. CommonClassesStrategy.php is including these as part of php-http package so it's trying to load them.

What is the correct approach to removing these dependencies without commenting out the includes manually?

The mailgun-php team posted the response below:

If you posted this issue on php-http/discovery you would gotten a much quicker reply.  The php-http/discovery package is doing a few class_exists() calls. I assume that is why you get this messages.

Can you recommend a way for me to stop this logging from happening cleanly?

Thanks,

Shaun.

**Comment by Nyholm** [comment] 2019-01-10 09:38
"mailgun-php". There is no such team working with the open source library. =)

The original issue is here: https://github.com/mailgun/mailgun-php/issues/488

What is your configured log level?

**Comment by dbu** [comment] 2019-12-27 19:55
the discovery component does not tamper with the log verbosity. `class_exists` normally does not even trigger a notice with the default composer class loader, maybe it is a "feature" of your monitoring or a custom class loader?

i will close the issue, as i think it is not caused by this component.

**Closed by dbu** 2019-12-27 19:55 UTC
